name: RealTime
main: net.nekomura.minecraft.Main
version: 1.0.0.0
description: Set Minecraft Time as Real Current Time.
author: Nekomura Huanying
softdepend: [PlaceholderAPI]

commands:
  realtime:
    aliases: [rt]
    usage: /realtime <args>
    description: plugin introduce
  gettime:
    usage: /gettime

permissions:
  realtime.*:
    children:
      realtime.admin: true
  realtime.admin:
    default: op